version: '3'

services:
  symfony:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - SYMFONY_ENV=dev
    depends_on:
      - mysql
    networks:
      - symfony
    extra_hosts:
      - "host.docker.internal:127.0.0.1"

  mysql:
    image: mysql:5.7
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony
      MYSQL_USER: rooter
    networks:
      - symfony

networks:
  symfony:
    name: symfony